import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Button from '../components/ui/button';
import Hero from '../components/ui/hero';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rekindl21</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles.hero}>
        {/* <div className={styles.bgImage}>
          <img src='/img/hero.png' alt='Rekindl21' />
        </div> */}
        <Hero>
          <div>
            <img src='/img/hero1.jpg' alt='' />
            <img src='/img/hero2.jpg' alt='' />
            <img src='/img/hero3.jpg' alt='' />
            <img src='/img/hero4.jpg' alt='' />
            <img src='/img/hero5.jpg' alt='' />
          </div>
        </Hero>
        <h1>
          Enrich your life by
          <br />
          <span>Rekindl</span>ing relationships.
        </h1>
        <Button>
          <Link href='about'>
            <a>Start Here</a>
          </Link>
        </Button>
      </div>

      <div className={styles.hero2}></div>
    </div>
  );
};

export default Home;
